apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-5skx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-5skx
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-5skx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-5skx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-5skx
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-xilt-tenant/appstudio/devfile-sample-python-basic-5skx@sha256:6f9f3b4f20cb28d1080bb2728b72f3b9f3e44f76abcced83b45277b9ab3576db
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
