apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ia2p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ia2p
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ia2p
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ia2p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ia2p
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-xilt-tenant/appstudio/dc-metro-map-ia2p@sha256:97a12f56f80fcf87b4352f2b832ee8878855bdd7db4b0f3adf6c54ad0dd7499d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
